[KARAF-3764] NoClassDefFoundError when the features-core bundle is refreshed by itself
Also fix problems with eventadmin and packageadmin causing refreshes of pax-logging-api and most of bundles at the start phase


Former-commit-id: 8723b8fd843040e7eed3fd9f887efd53727c0c3a