[KARAF-3350] Ignore NoClassDefFoundError caused by a refresh of the pax logging service bundle
Former-commit-id: 3107d0810f4e0b3e667e1edca6544902a037bde9